# Complete help on configuration: https://dystroy.org/bacon/config/

default_job = "run"

# Run clippy on the default target
[jobs.clippy]
command = [
    "cargo",
    "clippy",
    "--color",
    "always",
    "--features",
    "bevy/dynamic_linking",
]
need_stdout = false

# This job lets you run
# - all tests: bacon test
# - a specific test: bacon test -- config::test_default_files
# - the tests of a package: bacon test -- -- -p config
[jobs.test]
command = [
    "cargo",
    "test",
    "--color",
    "always",
    "--features",
    "bevy/dynamic_linking",
    "--",
    "--color",
    "always",
]
need_stdout = true
allow_warnings = true

[jobs.run]
command = [
    "cargo",
    "run",
    "--color",
    "always",
    "--",
    "--features",
    "bevy/dynamic_linking",
    # put launch parameters for your program behind a `--` separator
]
need_stdout = true
allow_warnings = true

# You may define here keybindings that would be specific to
# a project, for example a shortcut to launch a specific job.
# Shortcuts to internal functions (scrolling, toggling, etc.)
# should go in your personal global prefs.toml file instead.
[keybindings]
# alt-m = "job:my-job"
c = "job:clippy"
t = "job:test"
r = "job:run"
